language: php
php:
- 5.6
- 7.0
- 7.1
- 7.2
script: |
  composer install --optimize-autoloader --no-suggest
  phpunit
after_success: |-
  if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    echo Building documentation...
    rm -rf .git
    vendor/bin/phpdoc -d src/ -t .docs.xml/ --template=xml
    mkdir -p docs
    vendor/bin/phpdocmd .docs.xml/structure.xml docs
    git clone https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG.wiki.git .docs.old/
    mv -v .docs.old/.git docs/
    cd docs
    git config --global user.email "travis@travis-ci.org"
    git config --global user.name "Travis CI"
    mv ApiIndex.md Home.md
    git status
    git add *.md
    git commit -m "$TRAVIS_COMMIT_MESSAGE"
    git push
    cd ..
    rm -rf docs .docs.old .docs.xml
  fi;
env:
  global:
    secure: sHLGg2VWqUAE7aRD7QyrET/MN4XLZKmVaVtEb0E3odpuJCqiAzouudj/92FW9pJ4Y9gqyMMSiGwTjrbAchNkt90+9tTGVbc27bN2+F5PI1ItHhEISn4UNR8nPUdY0mpq7r0BxxlN38eoeS5xzYdG5Syh6W47Ix6PcVzndBLIUHfVZzey2QkeYDE3zIE82JFQNb7Eds32eGulCU6CsdcggcKwRIPgN9pFFC/nhsWyY1F0l5AnRVH8sSx8pkgwm7tia2G95LDjwxGzfdD2gs5r4Ue97E0oppB78Xf5Oudb7fLa/8mKwrs0hnFCDAKcYsg68NG/7MRN9tDjIHVGwulGi8kkUpBGwO9YGbzvpBN4NeaNPMvTXb/Peo6uwF5uQK+r8pNg19+cx5HfQifDwJbKGD873xkIj9gyskAEUBRa1OpXPG6YVxQjXxsQeO9uXpnd/adH9J4EWgaEGSrqFsK0aUcAoqFE5H4FEB6TZK40kJJ0+YgL6koy4MVcJMszRDOxZ6yTjpqv7r9Ua+xy+p6TK4MrOYbxrD3rLK48AObE1/Gkq4GPAT98zJGsqfaHDb2ANiy6B4UZwXpyTRJEujgCQHsVJ0r3uYq81oxe9I6AyZuF9W58IUETy20PX09Vrd7CwHnO1UwUHeIrlqcpZr7PiliZACf5iYtOFq6UWSrZXRI=
