language: php
php:
- 5.6
- 7.0
- 7.1
- 7.2
script: |
  composer install --optimize-autoloader --no-suggest
  phpunit
after_success: |-
  if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    echo Building documentation...
    rm -rf .git
    vendor/bin/phpdoc -d src/ -t .docs.xml/ --template=xml
    mkdir -p docs
    vendor/bin/phpdocmd .docs.xml/structure.xml docs
    git clone https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG.wiki.git .docs.old/
    cd .docs.old
    git rm *.md
    cd ..
    mv -v .docs.old/.git docs/
    cd docs
    git config --global user.email "travis@travis-ci.org"
    git config --global user.name "Travis CI"
    mv ApiIndex.md Home.md
    find *.md -type f -exec sed -i 's/\.md//g' {} \;
    git status
    git add *.md
    git commit -m "$TRAVIS_COMMIT_MESSAGE"
    git push
    cd ..
    rm -rf docs .docs.old .docs.xml
  fi;
env:
  global:
    secure: fjrEZA3hmu6Rv+V/0+owejoL3Ub8TllQtGAMLXpReCQur44RHr/3ErT/o+wQwWjYqV+zCfBEjsuCj/nrsC1I3fOCwHAN5DwtTWkyRNshdT1Rk9ocHoW/XGvNEtBG1p8Er++wOjvTptllbN4CzzdV6FoxIBq0zDtavsQ38EZmyBLabExXjQv1NC6bhLAHTmQJh8bWPjjWN1zLcymBGsXNyhjk6N1PM9VzdKuOyOEMyz8RvCADdra3iUl36YZyq0UFj0H6CH52nLtqPdyN7Nk1N0awcb/jsXXlmNy4kw57upVn10NBcP1oFxw4c/Zj46WWWlZKedFToxlb6l3YlX9S2Zrdbfsh+5GT5uZe4OrqX2ra2pTpNeVwik4gOjYcPanQTJGMZ89oOat51SSfhWQ8vYrJcGw/H2VjyMal4DdO85/u4Besu1lzdWtCHsMq2RPyO/oCD3LDpcVix7UzDj6vVi4Mjz3kZclOysS1u3e7c70e2n2w9LxrgdwehFaIRTaL+G8J1VjzYPKJ0QDWspBTUuPQBhi9st8S8CqIEzE/s0CDtsAumWeLFjY3bChv8ij59fI0l3aVjNYgNjG1ew69MFHlPQnPGrAdM3xiCtdRkP99kUe9yhBaZ2/vUTKi79bMY6zxGkigpwRITSUImL/T/3eaVLuVPKRuljHwrKmMLvs=
