language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

script: |
  composer install --optimize-autoloader --no-suggest
  phpunit

after_success: |
  if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    echo Building documentation...
    rm -rf .git
    vendor/bin/phpdoc -d src/ -t .docs.xml/ --template=xml
    mkdir -p docs
    vendor/bin/phpdocmd .docs.xml/structure.xml docs
    git clone https://github.com/$TRAVIS_REPO_SLUG.wiki.git .docs.old/
    mv -v .docs.old/.git docs/
    cd docs
    git status
    git add *
    git commit -m "$TRAVIS_COMMIT_MESSAGE"
    git push
    ls -a
    cd ..
    rm -rf docs .docs.old .docs.xml
  fi;