language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

script: |
  composer install --optimize-autoloader --no-suggest
  phpunit

after_success: |
  echo "$TRAVIS_BRANCH";
  if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    rm -rf .git
    vendor/bin/phpdoc  -d src/ -t xml-docs/ --template="xml"
    vendor/bin/phpdocmd xml-docs/structure.xml docs/
    git checkout https://github.com/$TRAVIS_REPO_SLUG.wiki.git old-docs/
    mv -v old-docs/.git docs/
    cd docs
        git status
        git add *
        git commit -m "$TRAVIS_COMMIT_MESSAGE"
        git push
	ls -a
    cd ..
    rm -rf docs old-docs xml-docs
  fi;