language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

script: |
  composer install --optimize-autoloader --no-suggest
  phpunit

after_success: |
  if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    echo Building documentation...
    echo Step #1
    rm -rf .git
    echo Step #2
    vendor/bin/phpdoc  -d src/ -t xml-docs/ --template="xml"
    echo Step #3
    vendor/bin/phpdocmd xml-docs/structure.xml docs/
    echo Step #4
    git clone https://github.com/$TRAVIS_REPO_SLUG.wiki.git old-docs/
    echo Step #5
    mv -v old-docs/.git docs/
    echo Step #6
    cd docs
    echo Step #7
    git status
    echo Step #8
    git add *
    echo Step #9
    git commit -m "$TRAVIS_COMMIT_MESSAGE"
    echo Step #10
    git push
    ls -a
    echo Step #11
    cd ..
    echo Step #12
    rm -rf docs old-docs xml-docs
  fi;